FF-1911 #time 5m ci: testing api testing docs

diff --git a/azure-pipelines.yml b/azure-pipelines.yml
--- a/azure-pipelines.yml
+++ b/azure-pipelines.yml
@@ -121,6 +121,12 @@ stages:
             npm i -g dredd
             ./api-testing.sh
             ./doc.sh
+        - script: |
+            if [ $? -ne 0 ]; then
+              echo "API testing failed"
+              exit 1
+            fi
+        - script: |
             export AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID_MAIN}
             export AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY_MAIN}
             aws s3 sync swaggerdocs s3://${DOCS_BUCKET_NAME}/swagger_api_documentation
@@ -128,7 +134,7 @@ stages:
           displayName: Unit Testing
         - script: |
             if [ $? -ne 0 ]; then
-              echo "Unit Testing failed"
+              echo "API testing failed"
               exit 1
             fi
           displayName: Check Unit Testing Status
