INDY-648 #time 5m ci: failing the pipeline if tdd fails

diff --git a/azure-pipelines.yml b/azure-pipelines.yml
--- a/azure-pipelines.yml
+++ b/azure-pipelines.yml
@@ -126,6 +126,10 @@ stages:
             pip3 install -r devops/dependency/python/requirements.txt || true
             pip3 install -r devops/dependency/python/requirements2.txt || true
             python generate-python-licenses.py
+            if [ $? -ne 0 ]; then
+              echo "API testing failed"
+              exit 1
+            fi
             aws s3 cp node-licenses.json s3://$DOCS_BUCKET_NAME/licences/node/licenses.json --profile "indyauction-main"
             aws s3 cp python-licenses.json s3://$DOCS_BUCKET_NAME/licences/python/licenses.json --profile "indyauction-main"
             aws cloudfront create-invalidation --distribution-id $DISTRIBUTION_ID --paths "/*" --profile "indyauction-main"
@@ -191,6 +195,10 @@ stages:
           displayName: Obtain AWS Credentials
         - script: |
             ./envs.sh
+            if [ $? -ne 0 ]; then
+              echo "API testing failed"
+              exit 1
+            fi
           displayName: 'Copy Environment Files'
         - publish: $(System.DefaultWorkingDirectory)/.env
           artifact: Environment
@@ -327,6 +335,10 @@ stages:
             chmod +x ./tdd-test.sh
             cat .env            
             ./tdd-test.sh  
+            if [ $? -ne 0 ]; then
+              echo "API testing failed"
+              exit 1
+            fi
             aws s3 sync coverage s3://$DOCS_BUCKET_NAME/backend-tdd-coverage  --profile "indyauction-main"
             aws cloudfront create-invalidation --distribution-id $DISTRIBUTION_ID --paths "/*" --profile "indyauction-main" --profile "indyauction-main"
           displayName: Run TDD Tests
