INDY-337 #time 15m ci: added credential process in dast

diff --git a/azure-pipelines.yml b/azure-pipelines.yml
--- a/azure-pipelines.yml
+++ b/azure-pipelines.yml
@@ -157,27 +157,84 @@ stages:
   
 - stage: Test
   jobs:
-    - job: APITesting
-      displayName: "Unit Testing"
+  #   - job: APITesting
+  #     displayName: "Unit Testing"
+  #     condition: and(or(contains(variables['System.PullRequest.SourceBranch'], 'feature'), contains(variables['System.PullRequest.SourceBranch'], 'ci'), contains(variables['System.PullRequest.SourceBranch'], 'bugfix'), contains(variables['System.PullRequest.SourceBranch'], 'hotfix')), succeeded())
+  #     pool:
+  #       vmImage: "ubuntu-22.04"
+  #     steps:
+  #       - task: UsePythonVersion@0
+  #         inputs:
+  #           versionSpec: '3.11'
+  #       - task: Cache@2
+  #         inputs:
+  #           key: 'npmV2 | "$(Agent.OS)" | package.json'
+  #           restoreKeys: |
+  #             npm | "$(Agent.OS)"
+  #           path: "$(System.DefaultWorkingDirectory)/node_modules"
+  #           cacheHitVar: CACHE_RESTORED
+  #         displayName: Cache npm
+  #       - script: npm config set registry https://registry.npmmirror.com
+  #       - script: |
+  #           npm install --cache .npm
+  #         condition: ne(variables.CACHE_RESTORED, 'true')
+  #       - task: DownloadPipelineArtifact@2
+  #         name: environment
+  #         inputs:
+  #           artifact: Environment
+  #           targetPath: '$(System.DefaultWorkingDirectory)'
+  #       - task: DownloadSecureFile@1
+  #         name: Certificate
+  #         displayName: 'Download certificate'
+  #         inputs:
+  #           secureFile: 'certificate.crt'
+  #       - task: DownloadSecureFile@1
+  #         name: Privatekey
+  #         displayName: 'Download private key'
+  #         inputs:
+  #           secureFile: 'private.key'
+  #       - bash: |              
+  #           wget https://rolesanywhere.amazonaws.com/releases/1.0.3/X86_64/Linux/aws_signing_helper
+  #           chmod +x aws_signing_helper
+  #         displayName: Install AWS Signer
+  #       - bash: |
+  #           aws configure set credential_process "$(pwd)/aws_signing_helper credential-process --certificate $(Certificate.secureFilePath) --private-key $(Privatekey.secureFilePath)  --trust-anchor-arn $TRUST_ANCHOR_ARN --profile-arn $PROFILE_ARN --role-arn $ROLE_ARN" --profile "$PROFILE_ENV"
+  #           echo "##vso[task.setvariable variable=AWS_SDK_LOAD_CONFIG]1"
+  #         displayName: Obtain AWS Credentials
+  #       - script: |
+  #           source .env
+  #           aws sts get-caller-identity --profile "$AWS_PROFILE"
+  #           pip3 install boto3 dredd_hooks python-dotenv requests pyjwt pyotp requests
+  #           npm i -g dredd
+  #           ./api-testing.sh
+  #           if [ $? -ne 0 ]; then
+  #             echo "API testing failed"
+  #             exit 1
+  #           fi
+  #           ./doc.sh
+  #         displayName: Unit Testing
+  #       - bash: |
+  #           aws configure set credential_process "$(pwd)/aws_signing_helper credential-process --certificate $(Certificate.secureFilePath) --private-key $(Privatekey.secureFilePath)  --trust-anchor-arn $TRUST_ANCHOR_ARN_MAIN --profile-arn $PROFILE_ARN_MAIN --role-arn $ROLE_ARN_MAIN" --profile "indyauction-main"
+  #           echo "##vso[task.setvariable variable=AWS_SDK_LOAD_CONFIG]1"
+  #           echo "##vso[task.setvariable variable=AWS_PROFILE]indyauction-main"
+  #         displayName: Obtain AWS Credentials
+  #       - script: |
+  #           aws configure list --profile "indyauction-main"
+  #           aws s3 sync swaggerdocs s3://${DOCS_BUCKET_NAME}/swagger_api_documentation --profile "indyauction-main" 
+  #           aws cloudfront create-invalidation --distribution-id $DISTRIBUTION_ID --paths "/*" --profile "indyauction-main"
+  #         displayName:  Unit Testing Documentation
+  
+    - job: "dast"
+      displayName: 'Dynamic Application Security Testing (DAST)'
+      dependsOn: APITesting
       condition: and(or(contains(variables['System.PullRequest.SourceBranch'], 'feature'), contains(variables['System.PullRequest.SourceBranch'], 'ci'), contains(variables['System.PullRequest.SourceBranch'], 'bugfix'), contains(variables['System.PullRequest.SourceBranch'], 'hotfix')), succeeded())
       pool:
-        vmImage: "ubuntu-22.04"
+          vmImage: "ubuntu-22.04"
       steps:
-        - task: UsePythonVersion@0
-          inputs:
-            versionSpec: '3.11'
-        - task: Cache@2
-          inputs:
-            key: 'npmV2 | "$(Agent.OS)" | package.json'
-            restoreKeys: |
-              npm | "$(Agent.OS)"
-            path: "$(System.DefaultWorkingDirectory)/node_modules"
-            cacheHitVar: CACHE_RESTORED
-          displayName: Cache npm
-        - script: npm config set registry https://registry.npmmirror.com
-        - script: |
-            npm install --cache .npm
-          condition: ne(variables.CACHE_RESTORED, 'true')
+        - checkout: self
+          clean: true
+          fetchDepth: 0
+          persistCredentials: true
         - task: DownloadPipelineArtifact@2
           name: environment
           inputs:
@@ -201,45 +258,6 @@ stages:
             aws configure set credential_process "$(pwd)/aws_signing_helper credential-process --certificate $(Certificate.secureFilePath) --private-key $(Privatekey.secureFilePath)  --trust-anchor-arn $TRUST_ANCHOR_ARN --profile-arn $PROFILE_ARN --role-arn $ROLE_ARN" --profile "$PROFILE_ENV"
             echo "##vso[task.setvariable variable=AWS_SDK_LOAD_CONFIG]1"
           displayName: Obtain AWS Credentials
-        - script: |
-            source .env
-            aws sts get-caller-identity --profile "$AWS_PROFILE"
-            pip3 install boto3 dredd_hooks python-dotenv requests pyjwt pyotp requests
-            npm i -g dredd
-            ./api-testing.sh
-            if [ $? -ne 0 ]; then
-              echo "API testing failed"
-              exit 1
-            fi
-            ./doc.sh
-          displayName: Unit Testing
-        - bash: |
-            aws configure set credential_process "$(pwd)/aws_signing_helper credential-process --certificate $(Certificate.secureFilePath) --private-key $(Privatekey.secureFilePath)  --trust-anchor-arn $TRUST_ANCHOR_ARN_MAIN --profile-arn $PROFILE_ARN_MAIN --role-arn $ROLE_ARN_MAIN" --profile "indyauction-main"
-            echo "##vso[task.setvariable variable=AWS_SDK_LOAD_CONFIG]1"
-            echo "##vso[task.setvariable variable=AWS_PROFILE]indyauction-main"
-          displayName: Obtain AWS Credentials
-        - script: |
-            aws configure list --profile "indyauction-main"
-            aws s3 sync swaggerdocs s3://${DOCS_BUCKET_NAME}/swagger_api_documentation --profile "indyauction-main" 
-            aws cloudfront create-invalidation --distribution-id $DISTRIBUTION_ID --paths "/*" --profile "indyauction-main"
-          displayName:  Unit Testing Documentation
-  
-    - job: "dast"
-      displayName: 'Dynamic Application Security Testing (DAST)'
-      dependsOn: APITesting
-      condition: and(or(contains(variables['System.PullRequest.SourceBranch'], 'feature'), contains(variables['System.PullRequest.SourceBranch'], 'ci'), contains(variables['System.PullRequest.SourceBranch'], 'bugfix'), contains(variables['System.PullRequest.SourceBranch'], 'hotfix')), succeeded())
-      pool:
-          vmImage: "ubuntu-22.04"
-      steps:
-        - checkout: self
-          clean: true
-          fetchDepth: 0
-          persistCredentials: true
-        - task: DownloadPipelineArtifact@2
-          name: environment
-          inputs:
-            artifact: Environment
-            targetPath: '$(System.DefaultWorkingDirectory)'
         - script: |
               git config --global user.email $BITBUCKET_EMAIL
               git config --global user.name $BITBUCKET_USER
